### ISSUE TITLE
Belt level determined by parent 

### ISSUE THREAD

**Issue by ShadedPL** [SmartFoundations/SmartIssueTracker#16]
Currently, when extending buildings all belt levels are the same, but ideally, for a better split of items + saving resources, the belt level to the machine should be smaller then the main belt.
My suggestion would be you make a building with the recipe, mergers/splitters in the desired places and belt (with the appropriate level) and when extending it keeps the belts level of the original and connects it with the pre-defined belt level.
I hope I'm making myself clear here, if not just hit me up on Discord :D

**Comment by majormer** [comment]
So you are saying that you might want Mk 1 belts going from the splitter to the input, and from the output to the merger, but have Mk 4 or 5 belts between the splitters and mergers so that you can accommodate the output from multiple buildings.  So, instead of assuming that you want to use the maximum belt level, or the global setting in the Smart! settings, you would want it to clone the machine you are pointing at for the extend.  Does that cover it, @ShadedPL ?

**Comment by ShadedPL** [comment]
That's exactly how I would see it @majormer. 
What I currently do now as a workaround is I set everything to MK1 and just upgrade the lines between the splitters afterwards.
I know that in the late-game this isn't a problem anyway when it comes to resources but it still helps balancing things out.

**Comment by Nykademos** [comment]
I also want this

**Comment by SmartFoundations** [comment]
This is a part of 19.4 update that can be found in SMM.
If this is what we were talking about here - let's close this issue

@ShadedPL

**Comment by ShadedPL** [comment]
Yes, this works even better than I have anticipated and invisioned, thank you so so much for the hard work you do!

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/17

Please follow up there.
