### ISSUE TITLE
A hotkey to toggle Smart! building on and off

### ISSUE THREAD

**Issue by Mister-Prime** [SmartFoundations/SmartIssueTracker#72]
**Is your feature request related to a problem? Please describe.**
I would like a way to toggle Smart building on/off. Sometimes I want to build single foundations or walls without the extra clicks or fighting against the Smart build hologram.

**Describe the solution you'd like**
Something like the way switching between Zoop mode and Default mode by pressing the R button.

**Describe alternatives you've considered**
Maybe an optional hotkey to let me temporarily disable Smart! building.

**Additional context**
What I am looking for is being able to temporarily get back to vanilla build behavior.

**Comment by snowboundmage2** [comment]
Double tap left shift?

**Comment by SmartFoundations** [comment]
Ok, so Auto-Connect logic can be disabled by double tapping shift(Primary)
When I'll find a way to disable the mod completely - I think I'll set this functionality to double tapping Secondary button(Ctrl or Alt)

**Comment by ShadedPL** [comment]
I think the major thing here is to switch between Smart! Zoop! and Default! because like Mister-Prime said there are situations where I like need to place just one block and with Zoop enabled I often end up with two blocks placed and having to delete the second one, which adds to the overall building time.
A temporary Smart! toggler would be great.

**Comment by Steppyx** [comment]
Exactly what I was thinking, this would really improve the quality of life in these small-build situations.

**Comment by SmartFoundations** [comment]
@ShadedPL  @Steppyx @Mister-Prime  
Check the latest version 19.5 b431 test  from SMM
If this is what you guys were talking about then close the issue

**Comment by Steppyx** [comment]
Yes, this is exactly what I, and I believe the others were talking about.
Since I cant close the issue, I might aswell add that if you disable the mod, it resets the setting for when to open the mod-settings screen to "Always". Not a big deal since I rebinded it to another key anyway, just wanna add it, in case you are not aware.
Thanks for the quick help!

**Comment by Mister-Prime** [comment]
Yeah, this little tweak does exactly what wanted. Totally rad! I'm gunna close this issue, then send you some beer money. This is a level of responsiveness that I never expected. Thanks so much!

**Comment by SmartFoundations** [comment]
@Mister-Prime  You are welcome! Thx

**Comment by majormer** [comment]
This issue has been migrated to the new repository.

**New location:** https://github.com/majormer/SmartFoundations/issues/71

Please follow up there.
